config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'profiles/:id' => 'profiles#show', as: :profile

  get 'profiles' => 'profiles#index'

  get 'profiles/index'

  get 'profiles/show'

  get 'tweets/index'

  get 'tweets/show'

  get 'tweets/edit'

  get 'tweets/new'

  get 'tweets/_form'

  resources :relationships

  resources :tweets do
    resources :likes
  end

  devise_for :users

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user #This is the current user that initiates the follow
	belongs_to :friend, class_name: "User" #This is the user being followed
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes

  validates :message, presence: true, length: { maximum: 140, too_long: 'A Tweet is a maximum of 140 characters. Duh.'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships
  has_many :inverse_relationships, 
  				class_name: "Relationship", 
  				foreign_key: "friend_id"
  has_many :inverse_friends,
  				through: :inverse_relationships
  				source: :user
  has_many :likes
  validates :username, presence: true, uniqueness: true

  def likes?(tweet)
  	tweet.likes.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location) }

  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location) }

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_tweet

  def create

  	@tweet.likes.where(user_id: current_user.id).first_or_create

  	respond_to do |format|
  		format.html { redirect_to request.referrer }
  	end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private

  def set_tweet
  	@tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@relationship = current_user.relationships.build( friend_id: params[:friend_id])

		if @relationship.save
			flash[:notice] = "Followed successfully"
			redirect_to profile_path(current_user.id)
		else
			flash[:notice] = "Unable to follow"
			redirect_to root_path
		end
	end

	def destroy
		@relationship = current_user.relationships.find(params[:id])
		@relationship.destroy
		flash[:notice] = "You have just completely destroyed your relationship!"
		redirect_to profile_path(current_user.id)
	end

	private

	def relationship_params
		params.require(:relationship).permit(:user_id, :friend_id)
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html {redirect_to @tweet, notice: "Tweet updated."}
      else
        format.html { render :edit }
      end
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.'}
      else
        format.html { render :new }
      end    
    end
  end

  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html {redirect_to tweets_url, notice: "Your Tweet has been destroyed."}
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

  def set_tweet
     @tweet = Tweet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/Shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
	<%= link_to "Unlike", tweet_likes_path(@tweet), method: :delete %>
<% else %>
<%= link_to "Like", tweet_likes_path(@tweet), method: :post %>
<% end %>

<%= @tweets.likes.count %>

Liked by:
<% @tweet.likes.each do |like| %>
	<br>
	<%= like.user.username %>
	<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetTweet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-xs" %>

  	<div class="container-fluid">
  		<%= yield %>
  	</div>

  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/profiles/index.html.erb
<h1>All The Users</h1>

<% @users.each do |user| %>
	<%= link_to user.username, profile_path(user) %><br>
<% end %>

app/views/profiles/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<% @user.tweets.each do |tweet| %>
	<%= tweet.message %><br>
<% end %>

<% if current_user.id != @user.id %>
	<% if current_user.friends.include?(@user) %>
		<%= link_to "Unfollow",
		 	relationship_path(current_user.relationships.find_by_friend_id(@user)), 
		 	method: :delete %>
	<% else %>
		<%= link_to "Follow", 
			relationships_path(friend_id: @user), 
			method: :post %>
	<% end %>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
	<% if @tweet.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:
			</h2>
			<ul>
				<% @tweet.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<!-- * This Part Is the Form * -->

<div class="field form-group">
	<%= f.label :message %><br>
	<%= f.text_field :message %>
</div>

<div class="field form-group">
	<%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="actions form-group">
	<%= f.submit class: "btn btn-sm btn-success" %>
</div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to "Back to Tweets Index", tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All The Tweets In The Universe</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Message</th>
			<th>User</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @tweets.each do |tweet| %>
		<tr>
			<td><%= tweet.message %></td>
			<td><%= tweet.user.username %></td>
			<td><%= link_to 'Show', tweet %></td>
			<td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
			<td><%= link_to 'Destroy', tweet, 
					method: :delete, 
					data: { confirm: "Are you sure?" } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-success" %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show This Tweet', @tweet%>
<%= link_to 'All Tweets', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Message: </strong>
	<%= @tweet.message %>
</p>

<p>
	<strong>User: </strong>
	<%= @tweet.user.username %>
</p>

<%= render 'Shared/likes' %>
<br>

<%= link_to "Edit This Tweet", edit_tweet_path(@tweet) %>
<%= link_to "All The Tweets", tweets_path %>